set_time:
  description: Set time on a LYWSD02
  fields:
    mac:
      description: BLE MAC Address of a LYWSD02
      example: "01:23:45:67:89:AB"
      required: true
    timestamp:
      description: UNIX Epoch Value Representing Desired Time
      example: 1702200346
    tz_offset:
      description: Timezone Offset in Hours
      example: -3
    temp_mode:
      description: C = Celsius, F = Fahrenheit
      example: "C"
    clock_mode:
      description: 12 or 24 hour operation
      example: 12